# Generated by Django 4.1 on 2022-08-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_brand_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="params",
            field=models.ManyToManyField(to="cars.detail"),
        ),
    ]
