# Generated by Django 4.1 on 2022-08-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=17, verbose_name="Себестоимость"
                    ),
                ),
                (
                    "margin",
                    models.PositiveSmallIntegerField(
                        default=1.1, verbose_name="Наценка"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, verbose_name="Себестоимость"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="car",
                        to="cars.car",
                        verbose_name="Машина",
                    ),
                ),
            ],
        ),
    ]
