# Generated by Django 4.1 on 2022-08-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_carprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carprice",
            name="id",
        ),
        migrations.AlterField(
            model_name="carprice",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                related_name="car",
                serialize=False,
                to="cars.car",
                verbose_name="Машина",
            ),
        ),
    ]
