# Generated by Django 4.1 on 2022-08-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_remove_carprice_id_alter_carprice_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="carprice",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carprice",
            name="car",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car",
                to="cars.car",
                verbose_name="Машина",
            ),
        ),
    ]
